Update petstore-pipeline.yml

diff --git a/pipeline-azure-devops/petstore-pipeline.yml b/pipeline-azure-devops/petstore-pipeline.yml
--- a/pipeline-azure-devops/petstore-pipeline.yml
+++ b/pipeline-azure-devops/petstore-pipeline.yml
@@ -217,7 +217,109 @@ jobs:
         imagescan
   - task: Bash@3
     displayName: Deploy & Monitoring
+    env:
+      DOCKER_USERNAME: $(DOCKER_USER)
+      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
+      BUILD_NUMBER: $(Build.BuildNumber)
+      DEPLOY_TOKEN: $(DEPLOY_TOKEN)
+      USER_ID: $(USER_ID)
+      USER_API_KEY: $(USER_API_KEY)
+      TENANT_URL: $(TENANT_URL)
     inputs:
       targetType: inline
-      script: "#!/bin/sh\n\nexport TENANT_SYSTEM_USER_NAME=\"${USER_ID}\"\nexport TENANT_SYSTEM_USER_API_KEY=\"${USER_API_KEY}\"\n\necho \"Reading order details from marketplace...\"\n\npython3 marketplace_order_reader.py\n\nexport mysql_url=$(cat db_url | base64)\nexport mysql_user=$(cat db_user | base64)\nexport petstore_host=$(cat fqdn)\nexport mysql_password=$(cat db_password | base64)\n\nmkdir -p chart_zip\n\nJPETSTOREWEB=\"${DOCKER_USERNAME}/azurejpetstoreweb:${BUILD_NUMBER}\"\n\nJPETSTOREDB=\"${DOCKER_USERNAME}/azurejpetstoredb:${BUILD_NUMBER}\"\n\ndeploy(){\n\n  echo \"Deploying application...\"\n  ls\n  \n  NAMESPACE=\"jppetstore\"  \n\n  docker logout\n  docker login -u \"${DOCKER_USERNAME}\" -p \"${DOCKER_PASSWORD}\"\n  kubectl delete job jpetstoredb --ignore-not-found -n $NAMESPACE --kubeconfig tmp_kube_config\n  helm package --destination chart_zip/modernpets ./helm/modernpets\n  \n  helm upgrade --install --wait --set image.repository=$DOCKER_USERNAME --set image.tag=$BUILD_NUMBER --set mysql.url=$mysql_url --set mysql.username=$mysql_user --set mysql.password=$mysql_password --set isDBAAS=True --set isLB=False --set httpHost=$petstore_host --namespace=$NAMESPACE --create-namespace $NAMESPACE --kubeconfig tmp_kube_config chart_zip/modernpets/modernpets-0.1.5.tgz\n  \n  echo \"\\n\\nYour application is available at http://jpetstore-web.${petstore_host}\\n\\n\"\n  \n  app=$(kubectl get  ingress -n $NAMESPACE --kubeconfig tmp_kube_config | base64 | tr -d '\\r')\n  app_decoded=$(kubectl get  ingress -n $NAMESPACE --kubeconfig tmp_kube_config | tr -d '\\r')\n  echo app running at $app_decoded\n  chmod +x result.sh\n  ./result.sh ${app}\n\n}\n\n\nstartdate=$(date +%s)\n(\n    set -ex\n    deploy\n)\nenddate=$(date +%s)\n\nrm -rf deploy_status\n\nif [ $errorCode -ne 0 ]; then\n    echo \"Application deploy has failed\"\n    echo \"failed\" >> deploy_status\nelse\n   echo \"Application deploy has succeded\"\n   echo \"success\" >> deploy_status\nfi\n\nexport DEPLOYMENT_STATUS=$(cat deploy_status)\nexport DEPLOY_DURATION_TIME=$((enddate - startdate))\nexport PROVIDER=\"Azure\"\nexport petstore_host=$(cat fqdn)\nexport DEPLOYMENT_HOSTNAME=\"http://jpetstore-web.${petstore_host}\"\nexport DEPLOYMENT_SERVICE_ID=\"petstore_on_aks_azure_devops\"\nexport DEPLOYMENT_HREF=\"http://jpetstore-web.${petstore_host}\"\nexport SERVICE_NAME=\"petstore_on_aks_azure_devops\"\nexport RUN_ID=$BUILD_NUMBER\n\npython3 ./publish_data/publish.py --deploy\n\nns=$(kubectl get ns --kubeconfig tmp_kube_config | grep monitoring | awk '{print $1}')\n\necho $ns\n\nif [ -z \"$ns\" ] || [ \"$ns\" != \"monitoring\" ]; then\n\n   echo \"Publishing monitoring tools...\"\n    \n    kubectl create ns monitoring --kubeconfig tmp_kube_config\n    kubectl apply -f ./prometheus -n monitoring --kubeconfig tmp_kube_config\n\n    sleep 1m\n\n    kubectl apply -f ./alertmanager/AlertManagerConfigmap.yaml -n monitoring --kubeconfig tmp_kube_config\n    kubectl apply -f ./alertmanager/AlertTemplateConfigMap.yaml -n monitoring --kubeconfig tmp_kube_config\n    kubectl apply -f ./alertmanager/Deployment.yaml -n monitoring --kubeconfig tmp_kube_config\n    kubectl apply -f ./alertmanager/Service.yaml -n monitoring --kubeconfig tmp_kube_config\n\nfi\n\n"
-...
+      script: >
+      
+        export TENANT_SYSTEM_USER_NAME="${USER_ID}"
+
+        export TENANT_SYSTEM_USER_API_KEY="${USER_API_KEY}"
+
+        echo "Reading order details from marketplace..."
+
+        python3 ./pipeline-common/marketplace_order_reader.py
+
+        export mysql_url=$(cat db_url | base64)
+        export mysql_user=$(cat db_user | base64)
+        export petstore_host=$(cat fqdn)
+        export mysql_password=$(cat db_password | base64)
+
+        mkdir -p chart_zip
+
+        JPETSTOREWEB="${DOCKER_USERNAME}/azurejpetstoreweb:${BUILD_NUMBER}"
+
+        JPETSTOREDB="${DOCKER_USERNAME}/azurejpetstoredb:${BUILD_NUMBER}"
+
+        deploy(){
+
+          echo "Deploying application..."
+          ls
+
+          NAMESPACE="jppetstore"  
+
+          docker logout
+          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
+          kubectl delete job jpetstoredb --ignore-not-found -n $NAMESPACE --kubeconfig tmp_kube_config
+          helm package --destination chart_zip/modernpets ./helm/modernpets
+
+          helm upgrade --install --wait --set image.repository=$DOCKER_USERNAME --set image.tag=$BUILD_NUMBER --set mysql.url=$mysql_url --set mysql.username=$mysql_user --set mysql.password=$mysql_password --set isDBAAS=True --set isLB=False --set httpHost=$petstore_host --namespace=$NAMESPACE --create-namespace $NAMESPACE --kubeconfig tmp_kube_config chart_zip/modernpets/modernpets-0.1.5.tgz
+
+          echo "\n\nYour application is available at http://jpetstore-web.${petstore_host}\n\n"
+
+          app=$(kubectl get  ingress -n $NAMESPACE --kubeconfig tmp_kube_config | base64 | tr -d '\r')
+          app_decoded=$(kubectl get  ingress -n $NAMESPACE --kubeconfig tmp_kube_config | tr -d '\r')
+          echo app running at $app_decoded
+          chmod +x result.sh
+          ./result.sh ${app}
+
+        }
+
+
+        startdate=$(date +%s)
+        
+        (
+            set -ex
+            deploy
+        )
+        
+        enddate=$(date +%s)
+
+        rm -rf deploy_status
+
+        if [ $errorCode -ne 0 ]; then
+            echo "Application deploy has failed"
+            echo "failed" >> deploy_status
+        else
+           echo "Application deploy has succeded"
+           echo "success" >> deploy_status
+        fi
+
+        export DEPLOYMENT_STATUS=$(cat deploy_status)
+        export DEPLOY_DURATION_TIME=$((enddate - startdate))
+        export PROVIDER="Azure"
+        export petstore_host=$(cat fqdn)
+        export DEPLOYMENT_HOSTNAME="http://jpetstore-web.${petstore_host}"
+        export DEPLOYMENT_SERVICE_ID="petstore_on_aks_azure_devops"
+        export DEPLOYMENT_HREF="http://jpetstore-web.${petstore_host}"
+        export SERVICE_NAME="petstore_on_aks_azure_devops"
+        export RUN_ID=$BUILD_NUMBER
+
+        python3 ./pipeline-common/publish_data/publish.py --deploy
+
+        ns=$(kubectl get ns --kubeconfig tmp_kube_config | grep monitoring | awk '{print $1}')
+
+        echo $ns
+
+        if [ -z "$ns" ] || [ "$ns" != "monitoring" ]; then
+
+           echo "Publishing monitoring tools..."
+
+            kubectl create ns monitoring --kubeconfig tmp_kube_config
+            kubectl apply -f ./prometheus -n monitoring --kubeconfig tmp_kube_config
+
+            sleep 1m
+
+            kubectl apply -f ./alertmanager/AlertManagerConfigmap.yaml -n monitoring --kubeconfig tmp_kube_config
+            kubectl apply -f ./alertmanager/AlertTemplateConfigMap.yaml -n monitoring --kubeconfig tmp_kube_config
+            kubectl apply -f ./alertmanager/Deployment.yaml -n monitoring --kubeconfig tmp_kube_config
+            kubectl apply -f ./alertmanager/Service.yaml -n monitoring --kubeconfig tmp_kube_config
+
+        fi
